name=VKassistent
version=1.0.0
author=Arctic_WAWES
maintainer=Arctic_WAWES
sentence=Library for creating VK bots on ESP8266/ESP32.
paragraph=Control devices via a VK bot without extra code.
category=Communication
url=https://github.com/ArcticWAWES/VKassistent
architectures=esp8266,esp32