name=VKassistent
version=1.5.0
author=Arctic_WAWES
maintainer=Arctic_WAWES
sentence=A library for controlling ESP32 via VK bot.
paragraph=Supports text commands, keyboards, attachments.
category=Communication
url=https://github.com/ArcticWAWES/VKassistent
architectures=esp32
includes=VKassistent.h